### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by liamcmitchell-sc**
Hi, I've picked your project to address iOS scrolling issues in our project. I wasn't happy with some of the code so I rewrote some things. I'm sending you a PR back in case you find any of it useful.

It has the same API except for the allowTouchMove option you added recently. My version allows scroll in any child of target element. I think this is a better default, even if it may be slower.

I removed flow types and all build related code because I thought it was unnecessary. This version is ES5 with CommonJS exports. All bundlers should be able to handle this.

Anyone can install this version with:
```
npm install https://github.com/liamcmitchell-sc/body-scroll-lock.git#50100ac
```

### CODE REVIEW

**Comment by Jokero** [comment]
Does your version support horizontal scroll in Safari on iOS?
https://github.com/willmcpo/body-scroll-lock/issues/61

**Comment by willmcpo** [comment]
Good one, nice that you found a way that works better for you.

For my own uses, I don't have a use case where I need to allow touch move for child elements, but I can see where it is useful, hence the allowTouchMove addition recently. 

Personally, I feel there would be users from both sides of the camp, hence it may be a good idea to have it remain opt-in, especially there may be performance implications even if you don't need to take the hit.

If anyone else has opinions, feel free to comment.

**Comment by liamcmitchell-sc** [comment]
@Jokero 
> Does your version support horizontal scroll in Safari on iOS?
No, to support that, we need to record the X position as well as Y and add two extra cases in the available scroll check: https://github.com/liamcmitchell-sc/body-scroll-lock/blob/master/bodyScrollLock.js#L92-L99

@willmcpo, the API of allowTouchMove requires implementations of allowTouchMove to implement the same available scroll checks that this library is doing. This is a lot to expect of consumers to enable correct scrolling.

I think the nicest behavior for consumers of this library is to provide the most complete solution by default. If performance is an issue, the next easiest API is to allow opt-out of checking children via boolean. For anything else, it makes sense to allow override of all logic via allowTouchMove function but this should be a last resort.

**Comment by willmcpo** [comment]
Sure - if that is preferred default, we can provide a default function to
return true?

**Comment by giulianovarriale** [comment]
I agree with @liamcmitchell-sc. The default behavior should allow to scroll in any child of target element.

**Pull request closed without merging**
