### PR TITLE
Avoid .mjs for module build

### PR DESCRIPTION
**Pull request by diachedelic**
I've read somewhere that providing a `.mjs` file (as we do in the `"module"` field) can cause issues with build systems which don't expect it. This swaps it for a `.esm.js` extension instead.

### CODE REVIEW

**Comment by bmbrina** [comment]
I was having the following issue: `TypeError: Object(...) is not a function` and I made the changes on this PR locally and it solved the issue. 

Seems like `import { disableBodyScroll, clearAllBodyScrollLocks } from 'body-scroll-lock'` were returning `undefinded` in my project.

Is there any plan to merge this any time soon?

**Comment by diachedelic** [comment]
@bmbrina thanks for testing! @willmcpo I will merge this, please publish at your convenience.

**Comment by Markovnin** [comment]
@diachedelic can you push to npm please?

**Comment by willmcpo** [comment]
thanks again @diachedelic - will push this shortly

**Pull request merged**
