### PR TITLE
add touchmove event listener to document.body

### PR DESCRIPTION
**Pull request by phelma**
fixes body-scroll-lock for ios safari

### CODE REVIEW

**Review by diachedelic — COMMENTED** [review]
What's going on on line 55/56?  Surely thats not right?

**Comment by phelma** [comment]
> What's going on on line 55/56? Surely thats not right?

No it isnt, i've updated

**Comment by natterstefan** [comment]
Hi @diachedelic, any chance this gets released soon? Looks like we experience similar issues on iOS currently.

**Comment by diachedelic** [comment]
@natterstefan @phelma hey all, can someone explain exactly why this patch is needed? Which versions of iOS safari require it? It certainly worked on previous versions.

**Comment by axyz** [comment]
any news on the topic? the library stopped working for us as well on IOS (both chrome and safari) and it was working some time ago even though the demo page seems to work correctly even today, maybe is a problem that presents itself on non trivial use cases with a slightly more complex DOM structure. I guess the demo page could have a modal implemented using a react portal (most likely one of the most common use cases) to check if it works correctly.

**Comment by willmcpo** [comment]
Can someone provide a demo page with a Modal that's not working in IOS?  

If that can be done, then I can help test/verify that this fix is good. 

It'd be nice to get to the bottom of this.

**Comment by willmcpo** [comment]
And also, does the solution posted in https://github.com/willmcpo/body-scroll-lock/issues/102 help? If so, is this PR's fix still needed?

**Comment by alxhghs** [comment]
#102 doesn't solve this for me

**Comment by willmcpo** [comment]
for those where it's not working, some code snippets to support the need for this PR would be helpful.

Otherwise, the mentioned problems will be assumed to be non-issues.

**Comment by felipeplets** [comment]
@willmcpo I've tested the changes in this PR and they also fix the issue I was having on iOS in which the scroll was not locking on Safari mobile.

**Pull request closed without merging**
