### PR TITLE
fix: add px to positional css values for ios devices

### LINKED ISSUE #182: disableBodyScroll: content scrolls back to top
I am using React and the current scroll position is lost when `disableBodyScroll` is called.
In other words when I disable scrolling using `bodyScrollLock.disableBodyScroll` the the content locks properly  **_but_** it also autoscrolls back to the top of the page.
I am using https://cdn.jsdelivr.net/npm/body-scroll-lock@3.0.3/lib/bodyScrollLock.min.js

I have recreated the issue on [CodePen here](https://codepen.io/ApoloPena/pen/yLeabpV).
I am expecting the current scroll position to be preserved.

### PR DESCRIPTION
**Pull request by mindnektar**
Fixes #182

### CODE REVIEW

**Comment by lincolnthree** [comment]
That would do it. Lol :) Nice catch.

**Comment by BwamNL** [comment]
Agree!

**Review by c4ndybar — APPROVED** [review]
Looks good.  Merge it!

**Review by willmcpo — APPROVED** [review]

**Comment by efimweb** [comment]
@willmcpo could you publish it to npm?

**Comment by sdennett55** [comment]
@willmcpo i'll give you $10 if you publish this to npm.

**Comment by lincolnthree** [comment]
This PR still has another bug:

[line 130](https://github.com/mindnektar/body-scroll-lock/blob/5b3ffa20efd6110afbb74fe46165f2638c648615/src/bodyScrollLock.js#L130) 

Same problem, needs `+ 'px'` added as a suffix.

**Comment by owenhoskins** [comment]
This fixed my https://github.com/willmcpo/body-scroll-lock/issues/182 for me. Would be handy to have this on NPM. Currently using it via `"body-scroll-lock": "https://github.com/willmcpo/body-scroll-lock#79c4cf2c956eb7d5cf8d54a03d12751bc6ac8aa3"` in my package.json

**Pull request merged**
