### PR TITLE
Correctly account for remaining target elements while unlocking scrolling

### PR DESCRIPTION
**Pull request by LarsDenBakker**
Fixes https://github.com/willmcpo/body-scroll-lock/issues/64

### CODE REVIEW

**Comment by daKmoR** [comment]
is anything blocking this?

**Comment by willmcpo** [comment]
Hi @LarsDenBakker - are you able to pull master and resolve conflicts?

Otherwise, your fix looks good, thanks.

**Comment by LarsDenBakker** [comment]
@willmcpo I've resolved the conflicts. I noticed you gave me merge rights, should I go ahead and merge this?

**Comment by willmcpo** [comment]
Nice thanks heaps. I'll publish a beta version first before pushing a new minor update.

**Comment by willmcpo** [comment]
@LarsDenBakker published body-scroll-lock@2.5.11-beta.2 - if you have no issues with it, I'll aim to publish before the end of the week

**Comment by LarsDenBakker** [comment]
Thanks! I've been using my branch without issues for a while.

**Pull request merged**
