### PR TITLE
allow event propagation while preserving functionality

### PR DESCRIPTION
**Pull request by cody-unger**
Allows event propagation, still fulfills the purpose stopPropagation was serving

### CODE REVIEW

**Comment by cody-unger** [comment]
see #29

**Comment by cody-unger** [comment]
Reading through #40 and #41, it seems like the allowTouchMove feature is no longer necessary with the changes in this PR (and the replacement provided in this PR is preferable, because touchmove events will propagate without allowing body scrolling).

**Comment by diachedelic** [comment]
@cody-unger are you aware that `allowTouchMove` is required for `<textarea>` and `<input type="range">` elements to function correctly (not just elements which listen for `touchmove`)?

**Comment by diachedelic** [comment]
I'm happy to test this if that isn't something you've overlooked

**Comment by cody-unger** [comment]
I hadn't seen that, but I tested and it seems like those elements work fine with my changes.

**Pull request closed without merging**
